Based on demo script [here](https://github.com/iobis/training/blob/master/odmr/script.R)
as presented by Pieter Provoost @ Ocean Data Management for Researchers 2018

```{r load libs}
# requires devtools::install_github("iobis/robis", ref="obis2")
# robis2 expects these to be loaded (?):
library(ggplot2)
library(tidyverse)
```

```{r basic Spio filicornis example}
sf <- robis::occurrence("Spio filicornis")
dim(sf)
#robis::map_ggplot(sf)
# TODO: how to inject output of map_leaflet() file here?
# by default this opens in browser at
# file:///tmp/RtmpY77nB4/viewhtml5e25d55bb8f/index.html

str(sf)
names(sf)
#View(sf)
# TODO: how to inject output of View() here?

table(sf$originalScientificName)
```

```{r more advanced Spio example}
library("magrittr")

spio <- robis::occurrence("Spio")
spio %>% dplyr::group_by(species)%>% dplyr::summarize(n(), mean(decimalLatitude))

ggplot2::ggplot(spio) + ggplot2::geom_point(ggplot2::aes(x=decimalLongitude, y=decimalLatitude))

# select one species
#spio %>% dplyr::filter(species == "Spio blakei") %>% robis::map_ggplot()

# === spatial query
# wkt geometry string creation tool: http://iobis.org/maptool/

mol <- robis::occurrence(
    "Mollusca",
    geometry = "POLYGON ((2.54333 51.07247, 2.10388 51.64189, 2.79053 51.80522, 3.36731 51.36149, 2.54333 51.07247))"
)
#robis::map_ggplot(mol)
```
```{r ggplot2 histograms}
ggplot2::ggplot(mol) + ggplot2::geom_bar(ggplot2::aes(date_year), width = 1)
ggplot2::ggplot(mol) + ggplot2::geom_bar(
    ggplot2::aes(date_year, fill = class), width = 1
) + ggplot2::scale_fill_brewer(palette = "Spectral")
```
```{r bathymetry from marmap}
library(marmap)
library(plotly)
library(robis)

res <- 0.2
xmin <- 158
xmax <- 180
ymin <- -55
ymax <- -30
nz <- getNOAA.bathy(lon1 = 158, lon2 = 180, lat1 = -55, lat2 = -30, resolution = res * 60)
nz <- t(nz)
x <- seq(xmin + res / 2, xmax - res / 2, by = res)
y <- seq(ymin + res / 2, ymax - res / 2, by = res)

geom <- sprintf("POLYGON ((%s %s, %s %s, %s %s, %s %s, %s %s))", xmin, ymax, xmin, ymin, xmax, ymin, xmax, ymax, xmin, ymax)
ha <- occurrence("Hoplostethus atlanticus", geometry = geom)
pc <- occurrence("Parapercis colias", geometry = geom)

plot_ly(z = ~nz, x = ~x, y = ~y) %>%
  add_surface(showscale = FALSE) %>%
  add_trace(data = ha, x = ~decimalLongitude, y = ~decimalLatitude, z = ~-minimumDepthInMeters, marker = list(color = "#ffcc00", size = 3), name = "Hoplostethus atlanticus") %>%
add_trace(data = pc, x = ~decimalLongitude, y = ~decimalLatitude, z = ~-minimumDepthInMeters, marker = list(color = "#ff3399", size = 3), name = "Parapercis colias")
```
```{r export as CSV}

#write.csv(mol, file = "mollusca.csv", row.names = FALSE)
```
